GIRAPH-1146: Keep track of number of supersteps when possible
apache/giraph pull request #36
Opened 2017-05-04 20:10 UTC by majakabiljo

Summary: In many cases we know how many supersteps are there going to be. We can keep track of it and log it with progress.

Test Plan: Ran a job, example log line:
 Data from 3 workers - Compute superstep 5 (out of 6): 171824 out of 1304814 vertices computed; 19 out of 252 partitions computed

2017-05-05 17:36 UTC, ikabiljo requested changes

2017-05-05 17:36 UTC, ikabiljo commented on giraph-block-app/src/main/java/org/apache/giraph/block_app/framework/block/EmptyBlock.java
> +    return new PieceCount(1);
should be 0

2017-05-05 17:36 UTC, ikabiljo commented on giraph-block-app/src/main/java/org/apache/giraph/block_app/framework/block/PieceCount.java
> +    return known ? count : Integer.MAX_VALUE;
this might easily lead to overflow if anything is done with this number.

You should either fatal (better), or return 1M or something here.

2017-05-05 17:36 UTC, ikabiljo commented on giraph-block-app/src/main/java/org/apache/giraph/block_app/framework/piece/delegate/DelegatePiece.java
> +    PieceCount ret = new PieceCount(0);
this should be 1, this executes all pieces simultaneously.

2017-05-05 17:36 UTC, ikabiljo commented on giraph-block-app/src/main/java/org/apache/giraph/block_app/framework/BlockUtils.java
> +      GiraphConstants.SUPERSTEP_COUNT.set(conf, pieceCount.getCount());
shouldn't it be pieceCount.getCount() + 1 ?

2017-05-05 17:54 UTC, majakabiljo commented on giraph-block-app/src/main/java/org/apache/giraph/block_app/framework/BlockUtils.java
> +      GiraphConstants.SUPERSTEP_COUNT.set(conf, pieceCount.getCount());
There will be X+1 supersteps, but they are going to be supersteps 0..X. Actually I can make +1 here and then -1 in the logging part to keep it clear.

2017-05-05 17:54 UTC, majakabiljo commented on giraph-block-app/src/main/java/org/apache/giraph/block_app/framework/block/PieceCount.java
> +    return known ? count : Integer.MAX_VALUE;
Good point, I'll throw instead

2017-05-09 23:17 UTC, ikabiljo approved these changes
shipit, minor comment inline

2017-05-09 23:17 UTC, ikabiljo commented on giraph-block-app/src/main/java/org/apache/giraph/block_app/framework/piece/delegate/DelegatePiece.java
> +  @Override
you don't need to extend, default is 1 for any piece :)

2017-05-10 14:32 UTC, closed without merging